const double rocketStartX = 100;
const double rocketStartY = 100;
const double rocketWidth = 60;
const double rocketHeight = 40;
const double gravity = 800;
const double jumpStrength = -300;
const double groundHeight = 200;
const double groundScrollingSpeed = 100;
const double buildingInterval = 2;
const double buildingGap = 300;
const double minBuildingHeight = 125;  // Changed from 50 to 25
const double maxBuildingHeight = 250;  // New constant added
const double buildingWidth = 60;
const double enemyPlaneWidth = 75;
const double enemyPlaneHeight = 45;
const double enemyPlaneSpeed = 150;
const double enemySpawnInterval = 3;